apiVersion: batch/v1
kind: Job
metadata:
  name: zap-dast-scan
  namespace: default
spec:
  template:
    spec:
      # --- CLAVE: Le damos permiso de escritura al usuario de ZAP (UID 1000) ---
      securityContext:
        fsGroup: 1000
      containers:
      - name: zap-scanner
        image: zaproxy/zap-stable
        command: ["zap-baseline.py"]
        args: 
          - "-t"
          - "http://devsecops-demo-service:8080"
          - "-I" 
        # Montamos la carpeta
        volumeMounts:
          - name: zap-workdir
            mountPath: /zap/wrk
      restartPolicy: Never
      # Creamos el disco temporal
      volumes:
        - name: zap-workdir
          emptyDir: {}
  backoffLimit: 1